= Supporting documents in the Directive (2014/24/EU)

How and when a contracting authority can ask for, or require the supporting documents is mentioned in several parts of the Directive, and the use cases are created based on this.

[[art59-4]]
Article 59, paragraph 4::
A contracting authority may ask tenderers and candidates at any moment during the procedure to submit all or part of the supporting documents where this is necessary to ensure the proper conduct of the procedure. +
+
Before awarding the contract, the contracting authority shall, except in respect of contracts based on framework agreements where such contracts are concluded in accordance with Article 33(3) or point (a) of Article 33(4), require the tenderer to which it has decided to award the contract to submit up-to-date supporting documents in accordance with Article 60 and, where appropriate, Article 62. The contracting authority may invite economic operators to supplement or clarify the certificates received pursuant to Articles 60 and 62.

[[art59-5]]
Article 59, paragraph 5::
Notwithstanding paragraph 4, economic operators shall not be required to submit supporting documents or other documentary evidence where and in so far as the contracting authority has the possibility of obtaining the certificates or the relevant information directly by accessing a national database in any Member State that is available free of charge, such as a national procurement register, a virtual company dossier, an electronic document storage system or a prequalification system. +
+
Notwithstanding paragraph 4, economic operators shall not be required to submit supporting documents where the contracting authority having awarded the contract or concluded the framework agreement already possesses these documents. +
+
For the purpose of the first subparagraph, Member States shall ensure that databases which contain relevant information on economic operators and which may be consulted by their contracting authorities may also be consulted, under the same conditions, by contracting authorities of other Member States.

Article 71::
Where necessary for the purposes of point (b) of paragraph 6 of this Article, the required information shall be accompanied by the subcontractors’ self-declarations as provided for in Article 59. The implementing measures pursuant to paragraph 8 of this Article may provide that subcontractors which are presented after the award of the contract shall provide the certificates and other supporting documents instead of the self-declaration.

Note 65::
At any time during the period of validity of the dynamic purchasing system, contracting authorities should be free to require economic operators to submit a renewed and updated self-declaration on the fulfilment of criteria for qualitative selection, within an adequate time limit. It should be recalled that the possibility foreseen in the general provisions on means of proof of this Directive to ask economic operators to submit supporting documents and the obligation to do so of the tenderer to which it has decided to award the contract also apply in the particular context of dynamic purchasing systems.

[[note84]]
Note 84::
The tenderer to which it has been decided to award the contract should, however, be required to provide the relevant evidence and contracting authorities should not conclude contracts with tenderers unable to do so. Contracting authorities should also be entitled to request all or part of the supporting documents at any moment where they consider this to be necessary in view of the proper conduct of the procedure. This might in particular be the case in two-stage procedures – restricted procedures, competitive procedures with negotiation, competitive dialogues and innovation partnerships - in which the contracting authorities make use of the possibility to limit the number of candidates invited to submit a tender. Requiring submission of the supporting documents at the moment of selection of the candidates to be invited could be justified to avoid that contracting authorities invite candidates which later prove unable to submit the supporting documents at the award stage, depriving otherwise qualified candidates from participation.
